<?php

namespace App\Filament\Resources\ContactFormResource\Pages;

use App\Filament\Resources\ContactFormResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ViewRecord;

class ViewContactForm extends ViewRecord
{
    protected static string $resource = ContactFormResource::class;

    protected function getActions(): array
    {
        return [
            Actions\EditAction::make(),
        ];
    }


    protected function mutateFormDataBeforeFill(array $data): array
    {
        $this->record->read = true;
        $this->record->save();
        $data['read'] = true;
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

}
